# Site settings
title: Day of the Jekyll
email: richard.ashby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A test space to try out new things...
baseurl: "/thoughts" # the subpath of your site, e.g. /blog/
url: "http://richashbyuk.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
